import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });
import Header from "@/components/Header/Header";
import UserProvider from "@/context/UserProvider";
import Footer from "@/components/Footer/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ToastContainer />
          <Header admin={process.env.ADMIN_EMAIL} />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
